package.json
src/components/AvailableConnections.js
src/components/modals/tokenModal.js
src/redux/actionCreators.js
src/redux/reducers/authorization.js
src/redux/reducers/resources.js
src/redux/saga/resources.js
src/redux/utils.js
src/styles/text.js

- Added error handling for connection errors
**Notes**
- Should I redefine selectors in tokenModal or pass them through in the component from APIConnections?
- Whatever makes the most sense to you is the best place to start

Handle API connection errors

---

src/components/TargetActionDetail.js
src/components/TargetActions.js

- Added code comments and cleanup for detail files
- N/A
**Notes**
- N/A

Detail Cleanup

---

package-lock.json
package.json
src/api/resources.js
src/components/AvailableConnections.js
src/components/TargetResourceBrowser.js
src/components/TargetSearch.js
src/components/modals/tokenModal.js
src/components/widgets/spinner.js
src/redux/actionCreators.js
src/redux/reducers/helpers/resources.js
src/redux/reducers/resources.js
src/redux/saga/resources.js
src/redux/saga/saga_root.js
src/redux/utils.js
src/styles/text.js

- Added source target search functionality
- Added search input to target resource browser component
**Notes**
- ~We need to pretty up the search button~
- ~Ask Mike about mixing textStyles and straight css~

Collection Search

---

package-lock.json
package.json
src/api/resources.js
src/components/HeaderMenu.js
src/components/TargetSearch.js
src/components/modals/tokenModal.js
src/components/widgets/ActionButton.js
src/components/widgets/ModalSubmitButton.js
src/components/widgets/SearchTextField.js
src/components/widgets/TokenTextField.js
src/redux/reducers/resources.js
src/styles/text.js

- Integrated Material to the existing UI
- npm install
**Notes**
- N/A

Material Integration

---

src/redux/reducers/resources.js

Detail Bug

---

src/components/widgets/ActionButton.js

- DARKEN ACTION BUTTONS ONHOVER
- N/A

Branks42 onHover Changes

---

src/components/DevelopmentPartners.js

- Partner images in `Development Partner` component are now clickable and open in new tabs
- N/A

Branks42 Clickable Partners

---

src/components/modals/DownloadModal.js

- Added error icon to download modal when failure occurs
- N/A
**Notes**

Prettify Download Error Message

---

src/components/modals/DownloadModal.js

- Now clearing Download data upon successful download as well as failures....
- N/A

Branks42 Download Bug Patch

---

src/components/widgets/UploadStepper/UploadDuplicateActionRadioButtons.js

- Style the Radio Buttons onHover
- N/A

Branks42 Upload Duplicate Hover

---

src/components/TargetResourceBrowser.js
src/components/widgets/UploadActionButton.js
src/components/widgets/UploadStepper/UploadButton.js

- Change `Upload New Project` to `Create New Project` for a bit more clarity.
- N/A

Change Verbiage

---

src/components/modals/DownloadModal.js
src/components/widgets/RetryActionButton.js

- Added a retry button if download fails
- N/A

Branks42 Retry Button (Download Modal)

---

src/components/AvailableConnections.js
src/components/SnackBar.js
src/components/widgets/ActionButton.js
src/components/widgets/LeftSpinner.js
src/components/widgets/ModalSubmitButton.js
src/components/widgets/SearchTextField.js
src/components/widgets/Spinner.js
src/components/widgets/UploadResultsContent.js
src/components/widgets/UploadStepper/UploadButton.js
src/components/widgets/UploadStepper/UploadDuplicateActionRadioButtons.js
src/components/widgets/UploadStepper/UploadSelectFile.js
src/components/widgets/UploadStepper/UploadStepConnector.js
src/components/widgets/UploadStepper/UploadStepper.js
src/components/widgets/UploadStepper/UploadStepperBackButton.js
src/components/widgets/UploadStepper/UploadStepperNextButton.js
src/styles/colors.js
src/styles/text.js

- Changed result icon colors
- Changed result messages
- Created universal color variables
- N/A
**Notes**
- N/A

Upload Result Changes

---

src/components/SnackBar.js
src/styles/colors.js

- Snackbar pop up on DL and UL errors
- NEW COLOR OPTION
- N/A

Branks42 Snackbar Errors

---

src/components/TargetActions.js
src/components/TargetResourceBrowser.js

- Remove upload buttons if the user doesn't own the resource
- N/A

Branks42  Remove Upload Buttons if User Doesn't Own Resource

---

src/components/modals/DownloadModal.js
src/redux/reducers/resources.js

Changed the state variable 'sourceDownloadContent' to 'sourceDownloadData'

sourceDownloadContent Refactor

---

src/components/TargetResourceBrowser.js

- Create New Project button is now displayed on all partners
- If target doesn't support upload, then the button is disabled
- N/A

Branks42 Create New Tweak

---

src/components/upload_stepper/UploadStepper.js

Branks42 Clean Up Stepper

---

src/App.js
src/components/AvailableConnections.js
src/components/action_buttons/DownloadActionButton.js
src/components/modals/DownloadModal.js
src/components/modals/TokenModal.js
src/redux/actionCreators.js
src/redux/reducers/authorization.js
src/redux/reducers/resources.js

- Moved Token Modal to highest component level
- Moved Download Modal to highest component level

Modal To Top Level

---

src/components/modals/DownloadModal.js
src/components/upload_stepper/UploadResultsContent.js
src/redux/actionCreators.js
src/redux/reducers/resources.js
src/redux/saga/download.js
src/redux/saga/upload.js

- Upload now handles all errors
- Download now handles all errors

Download/Upload Error Messages

---

src/components/modals/TokenModal.js

- You can now press Enter to submit tokens.
- N/A

Branks42 Press Enter

---

src/components/AvailableConnections.js
src/components/TargetResourceBrowser.js

- Better handle Resource Collection Errors if the error isn't token related.
- N/A

Branks42 Resource Collection Errors

---

src/components/TargetResourceBrowser.js

- Clean up TargetResourceBrowser
- Now UseEffect and set CSS and message as opposed to lengthy ternary checks
- N/A

Branks42 Clean TargetResourceBrowser

---

src/components/modals/DownloadModal.js

- Clean up console warnings
- N/A

Branks42 Clean Up Download Warnings

---

src/components/upload_stepper/UploadResultsContent.js
src/components/upload_stepper/UploadStepper.js
src/components/widgets/buttons/RetryButtons/RetryUploadButton.js

Patch bug with retry button if resource detail is open in background of new upload request.....

Branks42 Retry Bug

---

src/components/HeaderMenu.js

Feedback Link

---

src/components/TargetActionDetail.js
src/components/TargetActions.js
src/components/TargetResourceBrowser.js
src/components/action_buttons/DownloadActionButton.js
src/components/modals/UploadModal.js
src/components/widgets/buttons/RetryButtons/RetryDownloadButton.js
src/redux/reducers/helpers/resources.js
src/redux/reducers/resources.js

- All the lefts are gone
- N/A

Branks42 Renamepalooza 2 Electric Renamepalooza-oo

---

src/App.js
src/components/AvailableConnections.js
src/components/HeaderMenu.js
src/components/TargetActionDetail.js
src/components/TargetActions.js
src/components/TargetResourceBrowser.js
src/components/TargetSearch.js
src/components/action_buttons/DownloadActionButton.js
src/components/modals/DownloadModal.js
src/components/modals/TokenModal.js
src/components/upload_stepper/UploadButton.js
src/components/upload_stepper/UploadResultsContent.js
src/components/widgets/buttons/CancelButton.js
src/components/widgets/buttons/RetryButtons/RetryDownloadButton.js
src/components/widgets/buttons/RetryButtons/RetryUploadButton.js
src/components/widgets/headers/TargetResourcesHeader.js
src/redux/actionCreators.js
src/redux/reducers/targets.js
src/redux/saga/download.js
src/redux/saga/resources.js
src/redux/saga/saga_root.js
src/redux/saga/upload.js

- Brought back a bunch of changes that occurred during the split.
- Please don't make me list them out
- N/A
**Notes**
- N/A

Split Remnants

---

src/components/SnackBar.js

- Add snackbar for Transfer
- Add snackbar when actions are cancelled
- N/A

Branks42 Transfer/Action Cancel Snackbar

---

src/components/AvailableConnections.js

- Stopped error from persisting in the target browser even when you switch targets

Persisting Error

---

src/components/widgets/buttons/ResourceButton.js

- Files are no longer greyed out in the resource browser.....
- N/A

Branks42 Resource Browser Bug

---

src/components/modals/TokenModal.js

- When Token Modal opens back up don't show failed token

Hide Failed token

---

src/components/modals/DownloadModal.js
src/components/modals/TokenModal.js
src/components/widgets/buttons/CancelButton.js
src/redux/reducers/download.js
src/redux/reducers/upload.js

- Fixed bug where if you hit cancel quickly it failed
- Fixed bug where token input remained when switching targets if token not submitted

Download Bug

---

src/components/AvailableConnections.js
src/components/HeaderMenu.js
src/components/transfer/TransferResourceButton.js
src/components/transfer/stepper/TransferStepperTargets.js
src/components/widgets/buttons/ResourceButton.js

- Made clickable things look clickable by adding a pointer cursor to them on hover
- Available Connections has a tiny little animation

Clickable CSS

---

src/components/modals/DownloadModal.js
src/components/transfer/TransferRetryButton.js
src/components/transfer/stepper/TransferStepperResults.js
src/components/upload_stepper/UploadResultsContent.js
src/components/widgets/buttons/RetryButtons/RetryUploadButton.js
src/redux/reducers/download.js
src/redux/reducers/transfer.js
src/redux/reducers/upload.js

- Download/Upload/Transfer results all handle cancel failures

Cancel Failure

---

src/components/TargetActions.js

- Users no longer have the option to only transfer the Presqt created metadata file.
- N/A

Branks42 PRESQ_FTS_METADATA mania

---

src/components/modals/TokenModal.js
src/components/transfer/stepper/TransferStepperToken.js

- Tokens now entered in the modal are now treated like passwords
- N/A

Branks42 Hidden Tokens

---

src/api/download.js
src/components/modals/DownloadModal.js
src/components/modals/TransferModal.js
src/components/modals/UploadModal.js
src/components/transfer/stepper/TransferStepperResults.js
src/components/upload_stepper/UploadResultsContent.js
src/components/widgets/buttons/RetryButtons/RetryDownloadButton.js
src/components/widgets/list_items/SuccessListItem.js
src/components/widgets/list_items/WarningList.js
src/redux/reducers/download.js
src/redux/saga/download.js

- Integrated Download JSON endpoint
- Download has a pending status now.

Download JSON

---

src/components/modals/TransferModal.js
src/components/modals/UploadModal.js
src/components/transfer/stepper/TransferStepperResults.js
src/components/upload_stepper/UploadResultsContent.js
src/components/widgets/buttons/CancelButton.js
src/redux/reducers/transfer.js
src/redux/reducers/upload.js

- uploadStatus/transferStatus are changes as soon as cancel is hit

Cancel Fix

---

src/components/upload_stepper/UploadResultsContent.js

- Message should be header.....oopsie
- N/A

Bbois HeaderFix

---

src/components/TargetSearch.js

- Search message is more explicit about searching for title
- Added tooltip about search results

Search Details

---

src/components/modals/TokenModal.js
src/components/transfer/stepper/TransferStepperToken.js

- Toggle button to make tokens visible/not visible
- N/A

Peep Tokens

---

src/components/TargetSearch.js
src/components/modals/TokenModal.js
src/components/transfer/stepper/TransferStepperToken.js
src/components/widgets/buttons/SignOutButton.js
src/components/widgets/headers/TargetResourcesHeader.js
src/redux/actionCreators.js
src/redux/reducers/resources.js
src/redux/reducers/targets.js
src/styles/buttons.js

- Added a sign out button for each target for users who have multiple accounts
- New target action: CLEAR_TARGET
- Unrelated to ticket: Updated token visibility button to change color on hover
- Unrelated to ticket: Added Search Icon/Button to Search Bar
- N/A

Branks42 Sign Out

---

src/components/TargetSearch.js
src/styles/buttons.js

- Added refresh button in resource
- Disable search button if no search value

Clear Search and Refresh

---

src/App.js
src/api/eaasi.js
src/api/service.js
src/components/SnackBar.js
src/components/TargetActions.js
src/components/action_buttons/DownloadActionButton.js
src/components/action_buttons/ServicesSplitButton.js
src/components/modals/EaasiModal.js
src/components/widgets/buttons/RetryButtons/RetryDownloadButton.js
src/components/widgets/buttons/ServicesSplitButton.js
src/config.js
src/redux/actionCreators.js
src/redux/reducers/download.js
src/redux/reducers/eaasi.js
src/redux/reducers/main.js
src/redux/saga/download.js
src/redux/saga/eaasi.js
src/redux/saga/saga_root.js
src/redux/saga/services.js

- Added split services button
- Added EaaSI Modal
- New EaaSI actions/saga/redux...
- N/A

EaaSI Services

---

src/components/action_buttons/ServicesSplitButton.js

fixed button import

---

src/api/resources.js
src/components/TargetSearch.js
src/components/transfer/TransferResourceButton.js
src/redux/actionCreators.js
src/redux/saga/resources.js

- Implement drop down search options on the search bar
- Update actionCreators, saga, api calls
- N/A

Branks42 Search Options

---

src/components/TargetSearch.js
src/utils/isSpaces.js

- Little arrow turns
- No search if spaces

Search Enhancement

---

src/api/resources.js
src/api/transfer.js
src/components/TargetSearch.js

- Added full drop down functionality for search
- N/A

Search Dropdown

---

src/api/resources.js
src/components/TargetSearch.js

- Close the search dropdown menu on keystoke
- N/A

Branks42 Close Drop on Keystroke

---

src/components/download_stepper/DownloadStepperResults.js
src/components/widgets/buttons/RetryButtons/RetryDownloadButton.js

- They no longer blow up when pressed

Fix bug in Download Cancel/Retry Buttons

---

src/components/transfer/TransferResourceButton.js

- Updated for GitHub additions

Branks42 Transfer Resource Browser

---

src/components/transfer/TransferResourceButton.js

- Added GitLab hierarchy to Transfer Resource Browser

Branks42 GitLab Hierarchy in Transfer Modal

---

src/api/status.js
src/components/AvailableConnections.js
src/redux/actionCreators.js
src/redux/reducers/main.js
src/redux/reducers/statuses.js
src/redux/saga/saga_root.js
src/redux/saga/status.js

We got
* integration of the status endpoint
* graying out of targets when they can't be reached
* a list of errors in bright red letters
* re-checking the status every ten seconds

Rocky  status integration

---

src/App.js
src/api/keywords.js
src/components/TargetResourceBrowser.js
src/components/action_buttons/ServicesSplitButton.js
src/components/keyword_stepper/KeywordStepper.js
src/components/keyword_stepper/KeywordStepperResults.js
src/components/keyword_stepper/KeywordStepperSubmit.js
src/components/modals/KeywordModal.js
src/components/widgets/list_items/KeywordEnhancementList.js
src/components/widgets/list_items/KeywordsList.js
src/redux/actionCreators.js
src/redux/reducers/keywords.js
src/redux/reducers/main.js
src/redux/saga/keywords.js
src/redux/saga/saga_root.js

- Added Keyword Enhancement to front end
- Keyword Modal
- New actions, saga, api calls
- Keyword Stepper components
- N/A

Branks42 Keyword Enhancement

---

src/api/transfer.js
src/components/keyword_stepper/KeywordStepperSubmit.js
src/components/widgets/list_items/KeywordEnhancementList.js

- Added a `Select All` button to the Keyword Enhancement modal
- When keywords are selected, it becomes a `Deselect All` button 😮
- N/A

Branks42 Select All Button

---

src/components/keyword_stepper/KeywordEnhanceButton.js
src/components/keyword_stepper/KeywordStepper.js
src/components/keyword_stepper/KeywordStepperOptions.js

- New step in Keyword modal for `Keyword Agreement`
- N/A

Branks42 Keyword Enhancement Agreement

---

src/api/resources.js
src/components/TargetSearch.js

- Added Keyword Search
- Updated API call
- N/A

Branks42 Keyword Search

---

src/components/HeaderMenu.js

READTHEDOCS

---

src/api/transfer.js
src/components/transfer/TransferResourceButton.js
src/components/transfer/TransferRetryButton.js
src/components/transfer/TransferStartOverButton.js
src/components/transfer/stepper/TransferStepper.js
src/components/transfer/stepper/TransferStepperResults.js
src/components/transfer/stepper/TransferStepperTransferButton.js
src/components/widgets/buttons/KeywordActionRadioButtons.js
src/components/widgets/list_items/KeywordTransferList.js
src/redux/actionCreators.js
src/redux/saga/transfer.js

- Keyword Enhancement functionality on Transfer Modal
- Added Keyword Action Step
- Updated Transfer agreement to include keyword info
- New Keyword Lists
- N/A

Branks42 Keyword Enhancement Transfer

---

src/components/SnackBar.js
src/components/keyword_stepper/KeywordStepperResults.js

- Added snackbar and success message to keyword enhancement
- N/A

Branks42 Keyword Snackbar and Success Message

---

src/components/widgets/buttons/KeywordActionRadioButtons.js

- Changed Verbiage of Radio Buttons
- N/A

Branks42 Transfer Keyword Radio Buttons

---

src/components/keyword_stepper/KeywordStepper.js
src/components/keyword_stepper/KeywordStepperResults.js
src/components/widgets/list_items/KeywordEnhancementList.js
src/components/widgets/list_items/KeywordsList.js

- Back Button
- Lists are now the same font size
- N/A

Branks42 Back Button in Keyword Modal

---

src/components/widgets/list_items/KeywordEnhancementList.js
src/components/widgets/list_items/KeywordsList.js

- Fixed Keyword modal keyword spacing

Fixed Keyword Spacing

---

src/components/transfer/stepper/KeywordTransferKeywords.js
src/components/transfer/stepper/KeywordTransferSuggestList.js
src/components/transfer/stepper/TransferStepper.js

- Changed which payload keys keyword steppers were using

Keyword Bugs

---

src/components/transfer/stepper/KeywordTransferSuggestList.js

- Fixed error that was being thrown during manual enhancement when no keywords were available.

Manual Keyword Bug

---

src/components/AvailableConnections.js
src/components/TargetResourceBrowser.js
src/components/TargetSearch.js
src/components/widgets/buttons/ResourceButton.js
src/components/widgets/buttons/SignOutButton.js

- When a request is active, limit the possibility of clicking buttons that will have conflicting consequences

Request Limiting

---

src/App.js
src/api/announcements.js
src/components/WarningBar.js
src/components/transfer/TransferStartOverButton.js
src/config.js
src/redux/actionCreators.js
src/redux/reducers/announcements.js
src/redux/reducers/main.js
src/redux/saga/announcements.js
src/redux/saga/saga_root.js

- Added Server Down Warning Bar
- Added automatic check in on /announcments.txt server file

Add Server Down Message

---

src/components/transfer/stepper/TransferStepper.js
src/components/transfer/stepper/TransferStepperSelectResource.js
src/styles/text.js

- Made things less disambiguous for transfer stepper by being more specific in the texts

Transfer Stepper Text Change

---

src/redux/reducers/helpers/resources.js

- Slight tweak so front end doesn't break with back end changes
- n/a

Branks42 Resource Collection Tweak

---

package-lock.json
package.json
src/api/resources.js
src/components/TargetResourceBrowser.js
src/components/TargetSearch.js
src/redux/actionCreators.js
src/redux/reducers/resources.js
src/redux/saga/resources.js
src/redux/saga/saga_root.js

- Add pagination to front end
- Now in Resource Collection Browser
- Will need to add this to the transfer browser as well

Branks42 Pagination

---

src/components/TargetResourceBrowser.js
src/components/TargetSearch.js

- Disabled clicking pages if pendingAPIOperations
- N/A

Branks42 Disable Pagination

---

src/api/github_issues.js

- Format newlines with newline character
- N/A

Branks42  GitHub modal bug

---

src/components/bagit_stepper/BagitResults.js

- Provide more information to end user in BagIt modal
- N/A

Branks42 BagIt Modal Message

---

src/api/progress.js
src/components/download_stepper/DownloadStepperSubmit.js
src/components/modals/TokenModal.js
src/components/transfer/TransferRetryButton.js
src/components/transfer/stepper/TransferStepperTransferButton.js
src/components/upload_stepper/UploadButton.js
src/components/widgets/buttons/RetryButtons/RetryDownloadButton.js
src/components/widgets/buttons/RetryButtons/RetryUploadButton.js
src/redux/actionCreators.js
src/redux/reducers/download.js
src/redux/reducers/transfer.js
src/redux/reducers/upload.js
src/redux/saga/download.js
src/redux/saga/progress.js
src/redux/saga/saga_root.js
src/redux/saga/transfer.js
src/redux/saga/upload.js

- Removed unnecessary saga calls
- Clean up and improvements ✨ 
- N/A

Branks42 Progress Refactor

---

src/components/keyword_stepper/KeywordStepperResults.js

- Added messages to explain to user the process of keyword enhancement
- N/A

Messages on enhancement

---

src/redux/actionCreators.js
src/redux/reducers/helpers/removeDuplicateResources.js
src/redux/reducers/helpers/resources.js
src/redux/reducers/resources.js
src/redux/reducers/transfer.js
src/redux/saga/resources.js
src/redux/saga/transfer.js

- Updated how resource browser is building resources as we now bring children back in the detail payload
- Update actionCreators
- Update saga calls
- N/A

Branks42 New Children

---

src/redux/reducers/helpers/resources.js
src/redux/reducers/resources.js
src/redux/reducers/transfer.js

- Moved where the deep clone was occurring
- Remove dupes
- N/A

Branks42 Children Clean Up

---

src/components/modals/TokenModal.js

- `API tokens` is now a clickable link to bring users to the page at the target where they can make a token
- N/A

Branks42 Token Link

---

src/api/download.js
src/api/transfer.js
src/api/upload.js
src/components/download_stepper/DownloadStepper.js
src/components/download_stepper/DownloadStepperAgreement.js
src/components/download_stepper/DownloadStepperResults.js
src/components/download_stepper/DownloadStepperSubmit.js
src/components/eaasi_stepper/EaasiStepperSubmit.js
src/components/transfer/TransferRetryButton.js
src/components/transfer/TransferStartOverButton.js
src/components/transfer/stepper/TransferStepper.js
src/components/transfer/stepper/TransferStepperAgreement.js
src/components/transfer/stepper/TransferStepperResults.js
src/components/transfer/stepper/TransferStepperTransferButton.js
src/components/upload_stepper/UploadAgreement.js
src/components/upload_stepper/UploadButton.js
src/components/upload_stepper/UploadResultsContent.js
src/components/upload_stepper/UploadStepper.js
src/components/widgets/buttons/RetryButtons/RetryDownloadButton.js
src/components/widgets/buttons/RetryButtons/RetryUploadButton.js
src/redux/actionCreators.js
src/redux/saga/download.js
src/redux/saga/transfer.js
src/redux/saga/upload.js

- New step in all modals to offer users the option to be notified of process completion via email
- Update saga, actions, api calls
- New components for all action modals
- N/A

Branks42 Email Opt In

---

src/components/TargetSearch.js

- Search tooltip is no longer necessary as results are now paginated
- N/A

Branks42 Remove Tooltip

---

src/components/TargetResourceBrowser.js
src/components/transfer/TransferResourceBrowser.js

- Give the user the ability to input a page number to jump to
- N/A

Branks42 Page Number Input

---

src/components/TargetActionDetail.js

- Make better use of whitespace in `Resource Detail` component
- N/A

Branks42 Details Makeover

---

src/App.js
src/api/fairshare.js
src/api/fairshare_evaluator.js
src/components/AvailableConnections.js
src/components/action_buttons/ServicesSplitButton.js
src/components/fairshare_stepper/FAIRshareResultsContent.js
src/components/fairshare_stepper/FAIRshareStepper.js
src/components/fairshare_stepper/FAIRshareStepperResults.js
src/components/fairshare_stepper/FAIRshareStepperSubmit.js
src/components/modals/FAIRshareModal.js
src/components/transfer/TransferResourceBrowser.js
src/components/widgets/list_items/FAIRshareFailureMessageList.js
src/components/widgets/list_items/FAIRshareSuccessMessageList.js
src/components/widgets/list_items/FAIRshareTestsList.js
src/components/widgets/list_items/FAIRshareWarningMessageList.js
src/components/widgets/list_items/TestListItem.js
src/redux/actionCreators.js
src/redux/reducers/fairshare.js
src/redux/reducers/main.js
src/redux/saga/fairshare.js
src/redux/saga/saga_root.js

- Add FAIRshare Evaluator modal
- New actions/saga/api calls
- New Stepper components
- New TestList component
- N/A
⬇️ 
⬇️

Branks42 Fairshare Evaluator Service

---

src/components/transfer/stepper/TransferStepper.js
src/components/transfer/stepper/TransferStepperAgreement.js
src/components/transfer/stepper/TransferStepperNextButton.js
src/components/widgets/buttons/KeywordActionRadioButtons.js

- `none` option for keyword enhancement during transfer
- N/A

Branks42 No Keyword Option

---

src/api/fairshare.js
src/components/fairshare_stepper/FAIRshareStepperSubmit.js
src/redux/actionCreators.js
src/redux/saga/fairshare.js

- Users can receive an email of their FAIRshare Evaluator results
- N/A

Added email opt-in to FAIRshare modal

---

package-lock.json
package.json
src/components/modals/IssueModal.js

- Filter the body and title of the Issue modal for profanity
- N/A

Filter Profanity in Issues

---

src/components/action_buttons/ServicesSplitButton.js
src/components/fairshare_stepper/FAIRshareStepperSubmit.js

- Changed doi to identifier
- N/A

Changed doi to identifier

---

src/components/fairshare_stepper/FAIRshareResultsContent.js
src/components/widgets/list_items/TestListItem.js

- Test result icons added beside test name
- N/A

Branks42 FAIR modal more clear
